name: unbuntu

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone Submodule
      run: git submodule update --init --recursive

    - name: config
      env:
        CC: clang
        CXX: clang++
      run: mkdir build && cd build && cmake ..

    - name: build
      run: cd build && make -j 2

    - name: test
      run: cd build && ctest --output-on-failure -j 2
