name: unbuntu

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone Submodule
      run: git submodule update --init --recursive
      
    - name: Configure CMake
      
      run: cmake -B build
  
    - name: Build
      run: cmake --build build -j 2
      
    - name: CTest
      run: cd build && ctest --output-on-failure -j 2
